### ISSUE TITLE
Change operations `mean`, `std`, `substract`, `div`  in the StandardScaler to equistore operations

### ISSUE THREAD

**Issue by agoscinski** [lab-cosmo/equisolve#19] opened 2023-02-23 12:01 UTC
> unrelated to this PR, but why is the StandardScaler not implemented in terms of equistore operations? It looks like it is re-doing what should be equistore.mean, equistore.std, equistore.substract, equistore.div. Is something missing in the operations?

_Originally posted by @Luthaf in https://github.com/lab-cosmo/equisolve/pull/15#discussion_r1115537399_

**Comment by Luthaf** [comment] 2023-02-23 12:16
Duplicate of #18 =)

**Closed by Luthaf** 2023-02-23 12:16 UTC
